apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: openebs
    namespace: openebs
spec:
    interval: 5m
    releaseName: openebs
    chart:
        spec:

            chart: openebs
            version: 8.0.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values: {}