apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: snapshot-controller
  namespace: flux-system
spec:
  interval: 10m
  path: clusters\main\kubernetes\system\snapshot-controller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

