apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:S9rJbKLO8zi7sCOyTkNNx2aKbxhuWQCIPmHi+hkYlW+6tUCjH6katTiWjGynE8PyOiP162NgkO2fB3TZ6VDoWiU=,iv:2N9lOYCuk7nNRcuG6BiQvBYZcIRICIBE1EqZLsX8AyY=,tag:KvX51scrpx0tg4y/9wywwg==,type:comment]
    #ENC[AES256_GCM,data:Ebo9rVFUMuCOjnzGgnS6HBxXCF52p57tme9c9+E9UDrLDkEVrvk/2DdB0l8=,iv:E/Oyf1zSFGMprW3u4PoYeDeH1QKWf2iByOIkN6GQR30=,tag:yoxNrSNLhbYvhA9pfIcl/A==,type:comment]
    VIP: ENC[AES256_GCM,data:3+ibb7lGsA4Ntn3tr14=,iv:itplw2ZwYvDr9S00W0XTtOwoF8/VrDAYqpVoPkc8UPU=,tag:4bg2l0cRnDb1Gkhc2+sfFA==,type:str]
    #ENC[AES256_GCM,data:DJ5DK1CKsHXDDTmfkEpl0+FcHAgk1Yh5My4=,iv:uctjLfFRYGrUsFVNJ0rT/hfio6AZ54CD/ZhFjg4hSwQ=,tag:HX6F+Oz8UGCsBzyo3lgWvA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:mMbdRzZascF5neVms/g=,iv:WiS/HV/achR2dCxYjmMhob0YGwVyDyUtCUf9zGfew4k=,tag:D4ZMdqwBJ5b8yjMmFcDRNw==,type:str]
    #ENC[AES256_GCM,data:z74kt17qV86vQ2McCQwRdVxYDR9Baahm6EjgaANvfjk2jw==,iv:2B9p82odLTnM/8QQWI4YhS0wzGu1dU1zzbC7OLDm7C8=,tag:yW3RYgaL9zwxXkcVXPQgwA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:XT9jBY5gCrPgKYN8,iv:hG9UHKOsF7bxUEtDLE72UIVc/6BdP8L7TfpkjYPcfxg=,tag:/Yqbeov6gL274bNf171pAw==,type:str]
    #ENC[AES256_GCM,data:DUnjs+XgBExB4Qzny300a63Wrk0jrGQEVhENusj0JG5oYVFUiI/pJG6uOuWPW50=,iv:r378Kv+vmZO4zZu61ZsbESbBuudmom1/x8bOtoWIXCs=,tag:E2bAvUvH8beirsrz6/taoQ==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:/jQ23zMMA9SuS/D9du9iX+vHLEc6wYkOI3FQnws=,iv:rKQXZzA/zXtGJmaMKPtVR0NT2DV1Tbj6UcAUjnVJZio=,tag:JkhhjjM4m1QHCuZGo60S1A==,type:str]
    #ENC[AES256_GCM,data:/ibm6Q3jXzDNHQYqs+pnpIiiPJFvsERTYvwaln1YQk7l4X0Xt8T3vc0U7qexRUHyXSoK9XAw+XuqKJ0CaF0+xSBjqrGKQ4kq4iJlcT5c3as=,iv:Y9Jg47bSaxzXbybkgjwPhJas8N22wgYR6KKx01aknTo=,tag:JI0FbEtmR2SX/rJK+NWV8g==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:SlIb2GgKfkI08NzRgjQ=,iv:vhuGUSdismPw97KFZomw13Zpjd1OdSdK6VWJtCdDOQE=,tag:h7hNMtUjceFQCU8bRYsawQ==,type:str]
    #ENC[AES256_GCM,data:BkZlqBtvny7PgBzq6s847CtihQnnN1eXTJVJa3C/5Ss0Zv4ya7V6WN/emoLd4p30iQk9AtFNaUlUQJMoYnpgvg85ZBI=,iv:kgEBmGo4k+nvXSU1ymXsOpXktmAWcI+zLY35rjTy56w=,tag:F8rJdrtBBRLTqQ1FTgst7Q==,type:comment]
    KUBEAPPS_IP: ENC[AES256_GCM,data:nQNHkVbNHCKfD6/ccZ0=,iv:W/ZcW9sz3pctWz/gxVd8m9tRzHhKsGu6tYbRiv9+pgg=,tag:YP+D6GP03A6l+Gg5YWmQkQ==,type:str]
    #ENC[AES256_GCM,data:u4ls64STGE6P7Vp1Bk5JFbisOsoDXooCUg87KQG7Exdy9Q2hCWQWLuw70xR+lhHtozfTnOQlCnM=,iv:obHlVky2fkPHsfULbYJ2KduAxLy5dFPjsRdldPGV19g=,tag:rcoBaGtkumasyNU3kpbzrQ==,type:comment]
    #ENC[AES256_GCM,data:eEq47uOCVGOK7OtdNjNxKmhmR3INCQQj6Q==,iv:BkRBZIf4F8lLZ8eUZLmCwV6WBb4xwJIQvX3XZfdCf8A=,tag:ti8tkHvgVfeaAaKH7kU9jg==,type:comment]
    GITHUB_REPOSITORY: ""
    #ENC[AES256_GCM,data:10c4hU3ePCzk+/bYgw==,iv:J4ySRHBkLsEe1Jx0sWtkHgiko+kyQx8kQW6UHX8RQFY=,tag:WFgjM6O4mRc4Smavz5Vbng==,type:comment]
    PODNET: ENC[AES256_GCM,data:cbrjyeXVvvgTUjPq0A==,iv:YkMnMTQXm5OffQR03SC2IwB8qJxMc3q6rIfqgIyYIwo=,tag:iq27WwrEqOfwnWG3c1oPvQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:HBYrqHdOnyyTsWdg3g==,iv:nTBDXgx4b/KkaHuGkyc4c0uoS2Ij56OFnhGUj6sO5zE=,tag:pUeiTRMudlXmt4TKpix95Q==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age106duxawzmchqcr6pa8e0g3taemx9guhr2afyn7g8ewwshhf2yu0s93z2ag
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmOUhTaW41RjkxN1N1aTRt
            RjZHRmFEbzZJQVdNSU9pZFlTT042anlqampFClBRdEMxc0VqSUJVY2dTLyt4a0lr
            ZTZEZkRSVklFTGNGbUcyZzBMcGdFMXMKLS0tIFJlWCtiZ29XVmpUVGZxMUxYTXF3
            YWF2TDdVMVR6bTZrY1oxRmZWRUlvOE0KKyu+CfOO80a+cPQw1327VkBU9DiY55m1
            yaNz57PqDITDKA+r9CtIKupS/+w/DExdioQ3MJlEsVVDlsoZFbAvhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-26T15:14:33Z"
    mac: ENC[AES256_GCM,data:4kur6ZTRhCG/dTBUvzhxixaYd5X7uecjqolPOAywNBFsyzJk+tcH7oDBFJVhDRX89n47GF2XYf1KB+IzUPAnovqioheM/LkcCS+z0A9YjvmW3tcmb23r0ronc9zv3xxQsbM1j8GC7HpWdpOd0wcHdr8oO7/fSWzA7TyV2de6uQc=,iv:QVGCl9kYRQ9K6Dv2u5T+gvPsr2GdTS/7rKeZp5Mp+I0=,tag:eQVBUNIraeam/bvQssGCXg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
