apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:aGfohy2/cekeR+rKRwlsmAo9gKFGzGvsdKLoC11hJrpW0hTmGqdee+CrAye7AbnZD5UtFnsFmQKib/CLcLWDF/hpTpKH6kHeSLc4R9XfsHvxzP/O6M97Uj4VT9eMfn3iJmRGd2aeSV7F6pbbj3SMdLSaoDJEda1ppzCpM3UjLrGohOhQnRJhCHpQly4cX0Pq44orRLO1BkDAxGJIu5MCPCFCDKDGQ1YMZGUTi+dQ+LCfwrzD7sbs4NjVog6Bn2PyDymWW6JagU8xrzpZNqJ3UkQ6phamUjzAaAVbLC3805DnRrBXuEyW8RsdKMg6e8VTIid//IqAWRAyilOuFlA4f0oFq475gHCAij88YwbjWGixW7WVf0gFIf/hmzQJNoVN,iv:8CrrUgsB5iBanPSsWmjshtAObiTjjrjeKMKpAY0w0vU=,tag:gNpK1RynuDuL1WYzJ2tJYw==,type:str]
    identity.pub: ENC[AES256_GCM,data:k8y/H51Nu326Vgr1DOiOrFny2tD6d8u1ejMH7eq9Kk7/8dVop5EuyZpMxeHxrRi6XBN2UX6jjoPrwLcDsN3V83bNHsZL5W2p6nb73lLStSEb6bhf3LJqcbwkl5REXMccNJhsD4C8rtpBznDUzm8Jz6VKLu3x7znvOA5udC1ShguUIdtrqn9Qe9vDYBRfpRxmunO3gZ2PbRlFR4WsG6/gxn+S7NlhfCTGCUnM0pbnabf38v65hmXecgY0IwrqcM66cnksQJCs+ku5l+0BLg==,iv:ju66rofgUXXgZIx3dhlYUpU6gRpUj1wrozkzu7+7Ohc=,tag:RBf1ohnfh8hlXSTc1ysqPQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:iw6xPvqd1R32XrwzX4cGLfpAlqVSfuiXk87jO2gzkbrc7i2G775DtijKad3b5bLu9Zr/WvlFjMfbeWyPwhhDy4rnpPtuIFifXnamD+kfXfHya76Mv1wm0dYIz2ZXcY1kj8fkwbrWG7lVeKgU3WCYxH0uP9XDv/hly0v+c6biiH8kKbWC86R+qTiXsMF0szmHnJGfrcFrvE4c+b5mWvCKf0KoMMU0Cws50IIG,iv:HopZq6XJ5a/Xn5Y7rBLt5QverC2BDKprEsRVjXvP/NI=,tag:pF+JNWjA9eaqMXiXZxrCag==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age106duxawzmchqcr6pa8e0g3taemx9guhr2afyn7g8ewwshhf2yu0s93z2ag
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZ2hwajhzazk2L3lxSm1n
            K1oyR3pGemRYNzN4bTk5Z0RNSlY2MlNrNVZzCm5xUDcySGQ1Vk1WOURocGVHWHFT
            NCtMWjJROFhnenFjQXhSODEyUjBGaVkKLS0tIFk5dlNIWGhab3B0K2svZlovNVNP
            MEVwVktqRWMweFZmMmFESFc1TGxBbkkKvguPI5V+AP7/nj+Z0IvEp0q8zs8vaHkL
            4KCnIw+bAZyr3UUcRf1t/FwCGwjH04PGBd7OcBh1xkmQ3yQHaeM81g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-26T15:04:18Z"
    mac: ENC[AES256_GCM,data:JzK6U3Zvq+PBeN8gvvb1HzPoCPN3V1KLFGZVautxFVal1v15lBaxuH6H2EENVqb5nw2LUy0vrGWBPxlv/4gSmnwrKz78lPwFUf5SmQCqGmierPkrwAXMqlaB1IWR4uNd5g9NQsal6143v22aO0zbgtd5luHpAwXMWI31bQOuiXI=,iv:GPAmiilsX+DsHAZ9PwCsD5aof4nQ4qyhp/V+fHvs9LE=,tag:kOiFi+UEw/bfKhHeg85D5g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
